---
version: 2.1
jobs:
    terraform:
        docker:
          - image: codaprotocol/coda-automation:manual
            environment:
                TESTNET: smoke_test
        steps:
            - checkout
            - run:
                name: terraform init
                command: cd terraform/testnets/testnet-smoke-test && terraform init
            - run:
                name: terraform refresh
                command: cd terraform/testnets/testnet-smoke-test && terraform refresh
            - run:
                name: terraform destroy -auto-approve
                command: cd terraform/testnets/testnet-smoke-test && terraform destroy -auto-approve
            - run:
                name: terraform plan
                command: cd terraform/testnets/testnet-smoke-test && terraform plan
            - run:
                name: terraform apply -auto-approve
                command: cd terraform/testnets/testnet-smoke-test && terraform apply -auto-approve
            - run:
                name: Apply Failed - Destroy
                command: cd terraform/testnets/testnet-smoke-test && terraform destroy -auto-approve
                when: on_fail
    ansible:
        docker:
          - image: codaprotocol/coda-automation:manual
            environment:
                TESTNET: smoke_test
        steps:
            - checkout
            - run:
                name: ssh config
                command: |
                    mkdir -p ~/.ssh
                    echo -e "$TESTNETPEM" > ~/.ssh/id_rsa
                    chmod 0600 ~/.ssh/id_rsa
                    echo -e "Host *.amazonaws.com\n  StrictHostKeyChecking no\n  UserKnownHostsFile /dev/null\n  User admin" > ~/.ssh/config
            - run:
                name: elastic_whitelist
                command: |
                    echo ${ELASTICJSON} > scripts/elastic_whitelist_config.json
                    cd scripts
                    ../ansible/ec2.py > ec2.json
                    ./elastic_whitelist.py
            - run:
                name: instances2inventory
                command: cd scripts && ./instances2inventory.py smoke-test
            - run:
                name: ansible init
                command: cd ansible && ./play coda-init.yaml
            - run:
                name: ansible start
                command: cd ansible && ./play coda-start-all.yaml
            - run:
                name: Wait 5 min for network to actually do something
                command: sleep 300
                no_output_timeout: 30m
            - run:
                name: ansible monit (starts joiners)
                command: cd ansible && ./play coda-monit.yaml
            - run:
                name: Wait 5 min for joiners
                command: sleep 300
                no_output_timeout: 30m
    check-status:
        docker:
          - image: codaprotocol/coda-automation:manual
            environment:
              TESTNET: smoke_test
        steps:
            - checkout
            - run:
                name: ssh config
                command: |
                    echo -e "$TESTNETPEM" > ~/.ssh/id_rsa
                    chmod 0600 ~/.ssh/id_rsa
                    echo -e "Host *.amazonaws.com\n  StrictHostKeyChecking no\n  UserKnownHostsFile /dev/null\n  User admin" > ~/.ssh/config
            - run:
                name: coda client status
                command: cd ansible && ./adhoc tag_testnet_smoke_test "coda client status"
            - run:
                name: New block test
                command: cd ansible && ./adhoc tag_testnet_smoke_test "./scripts/test-new-blocks.sh"
                no_output_timeout: 30m

            # FIXME: make a txn, make sure it succeeds.

            - run:
                name: Tail Logs
                command: cd ansible && ./adhoc tag_testnet_smoke_test "tail -n 100 test-coda/coda.log"
                when: on_fail
            - run:
                name: Tests Failed - destroy
                command: cd terraform/testnets/testnet-smoke-test && terraform destroy -auto-approve
                when: on_fail
    destroy:
        docker:
          - image: codaprotocol/coda-automation:manual
            environment:
              TESTNET: smoke_test
        steps:
            - checkout
            - run:
                name: terraform init
                command: cd terraform/testnets/testnet-smoke-test && terraform init
            - run:
                name: terraform refresh
                command: cd terraform/testnets/testnet-smoke-test && terraform refresh
            - run:
                name: Tests Failed - destroy
                command: cd terraform/testnets/testnet-smoke-test && terraform destroy -auto-approve

workflows:
    version: 2
    smoke-test-auto:
        jobs:
            - terraform
            - ansible:
                requires:
                    - terraform
            - check-status:
                requires:
                    - ansible
        triggers:
          - schedule:
              cron: "0 12 * * *" # 12 UTC
              filters:
                branches:
                  only: master

    smoke-test-destroy:
        jobs:
            - destroy
        triggers:
          - schedule:
              cron: "0 20 * * *" # 20 UTC
              filters:
                branches:
                  only: master