# maxmind geoip updater deb

- name: Download carbon installer
  get_url:
    url: "https://packagecloud.io/install/repositories/raintank/raintank/script.deb.sh"
    dest: /tmp/carboninstaller.sh
    force: no

- name: Install carbon repository
  command: bash /tmp/carboninstaller.sh
  sudo: true

- name: Run carbon
  command: sudo apt-get install carbon-relay-ng=0.11.0-1
  become: true
  register: apt_status
  until: apt_status|success
  delay: 6
  retries: 10

- name: Fix carbon /var/run perms
  command: chown carbon-relay-ng:carbon-relay-ng /var/run/carbon-relay-ng
  become: true

- name: Copy storage-schemas.conf Config
  become: true
  copy:
    dest: /etc/carbon-relay-ng/storage-schemas.conf
    content: |
        [default]
        pattern = .*
        retentions = 2m:14d

- name: Copy carbon-relay-ng.conf Config
  become: true
  copy:
    dest: /etc/carbon-relay-ng/carbon-relay-ng.conf
    content: |
        instance = "${HOST}"
        max_procs = 2
        pid_file = "/var/run/carbon-relay-ng/carbon-relay-ng.pid"
        spool_dir = "/var/spool/carbon-relay-ng"
        log_level = "info"
        listen_addr = "0.0.0.0:2003"
        plain_read_timeout = "2m"
        validate_order = false
        bad_metrics_max_age = "24h"

        [[route]]
        key = 'grafanaNet'
        type = 'grafanaNet'
        addr = 'https://graphite-us-central1.grafana.net/metrics'
        apikey = '8246:{{ grafana_graphite_api }}'
        schemasFile = '/etc/carbon-relay-ng/storage-schemas.conf'

        [instrumentation]
        graphite_addr = "localhost:2003"
        graphite_interval = 10000  # in ms

- name: Restart Carbon Relay
  command: systemctl restart carbon-relay-ng
  become: true

- name: Install graphyte
  command: pip3 install graphyte
