---
- hosts: all
  vars:
    elastic_endpoint: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32323930666537303264343134643161316435333361383632663736336232303035633662336161
          3434306263313764636564303038323731666531653465630a643930373733613263396234626561
          36346563663433386664396230366238313364613935363965353332386136333037363937346339
          3231666535616230640a656135386235313534376534393735656436623662613937303431663563
          62373033306566303365313765393635303462396164373232626531323863396133663465386530
          39366638366161316462653630666635313230616266636666643930353235376132356233663062
          62323466393630346634373733336639353761353464623137326263303236633135343733626266
          37353063336438316165
    s3_key_bucket: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39323063353432636535616535393536613333633166363936396238353536383439336666653165
          3733656236633363323838626662343139353431353163390a663065616435393966653234323232
          37353233656235643534656631343362613263396532626565353463376238306139646465393466
          6535386336653336330a653662613534303038383831663838373932646136343635616337646366
          33616639383930373163653438633037313464643534653030313437633238643163323962633561
          39353462623133303966343161373330663030306538633838636161316530366664363631326261
          646265326131346432613633653836333737
  strategy: free
  gather_facts: no
  tasks:
    - include: tasks/task-varlibcoda.yaml
    - include: tasks/task-pvdownload.yaml
    - include: tasks/task-pvextract.yaml
    - include: tasks/task-installcoda.yaml
    - include: tasks/task-testkeys.yaml
    - include: tasks/task-sshkeys.yaml
    - include: tasks/task-tools.yaml
    - include: tasks/task-install-filebeat.yaml

# Assign a unique ID to each proposer (so proof of stake works)
- hosts: proposers
  gather_facts: no
  tasks:
    - name: Unique ID
      copy:
        dest: /etc/coda-proposer_order
        content: "{{ ansible_play_hosts.index(inventory_hostname) }}"
      become: true
