---
- hosts: "tag_testnet_{{ netname }}"
  gather_facts: no
  tasks:
    - ec2_metadata_facts:
    - name: Generating coda_start.sh
      vars:
        seed_ip: "{{ hostvars[groups['tag_role_seed'][0]].ec2_ip_address }}"
        snark_leader_ip: "{{ hostvars[groups['tag_role_snarker'][0]].ec2_ip_address }}"
      template: "src=coda_start.sh.j2 dest='/home/admin/coda_start.sh' owner=admin group=admin mode=0755"
      tags: coda_start
    - pause:
        seconds: 5

- hosts: "tag_{{ netname }}_role_seed"
  gather_facts: no
  tasks:
    - name: Start Coda
      shell: /home/admin/coda_start.sh
      args:
        executable: /bin/bash
    - pause:
        seconds: 5

- hosts: "tag_{{ netname }}_role_snarker"
  gather_facts: no
  tasks:
    - name: Start Coda
      shell: /home/admin/coda_start.sh
      args:
        executable: /bin/bash
    - pause:
        seconds: 5

- hosts: "tag_{{ netname }}_role_proposer"
  gather_facts: no
  tasks:
    - name: Start Coda
      shell: /home/admin/coda_start.sh
      args:
        executable: /bin/bash
