---
- hosts: "tag_testnet_{{ netname }}"
  #vars:
    #proving_key_url: "{{ lookup('aws_secret', 'testnet/proving/s3_url') }}"
    #elasticsearch_endpoint: "{{ lookup('aws_secret', 'testnet/' + netname + '/elasticsearch/endpoint') }}"
    #kibana_endpoint:
  strategy: free
  gather_facts: no
  tasks:
    - name: "get proving url from secretsmanager"
      shell: "aws secretsmanager get-secret-value --secret-id 'testnet/proving/s3_url'"
      register: proving_url
      delegate_to: 127.0.0.1
    - name: "get elasticsearch endpoint from secretsmanager"
      shell: "aws secretsmanager get-secret-value --secret-id {{'testnet/' + netname + '/elasticsearch/endpoint'}}"
      register: elasticsearch_endpoint
      delegate_to: 127.0.0.1
    - name: "get kibana endpoint from secretsmanager"
      shell: "aws secretsmanager get-secret-value --secret-id {{'testnet/' + netname + '/kibana/endpoint'}}"
      register: kibana_endpoint
      delegate_to: 127.0.0.1
    - set_fact:
        proving_url: "{{ proving_url.stdout | from_json | json_query('SecretString')  }}"
    - set_fact:
        elasticsearch_endpoint: "{{ elasticsearch_endpoint.stdout | from_json | json_query('SecretString')  }}"
    - set_fact:
        kibana_endpoint: "{{ kibana_endpoint.stdout | from_json | json_query('SecretString')  }}"
    - include: tasks/task-varlibcoda.yaml
    - include: tasks/task-pvdownload.yaml
    - include: tasks/task-pvextract.yaml
    - include: tasks/task-installcoda.yaml
    - include: tasks/task-testkeys.yaml
    - include: tasks/task-sshkeys.yaml
    - include: tasks/task-tools.yaml
    - include: tasks/task-install-filebeat.yaml
    - include: tasks/task-install-metricbeat.yaml

# Assign a unique ID to each proposer (so proof of stake works)
- hosts: "tag_{{ netname }}_role_proposer"
  gather_facts: no
  tasks:
    - name: Unique ID
      copy:
        dest: /etc/coda-proposer_order
        content: "{{ ansible_play_hosts.index(inventory_hostname) }}"
      become: true
